Repository STEMMechanics/STEMCraft-Core, pull requests merged in 2023-11, with the labels that each got.

#28 add ability to link world inventories
  README.md
  pom.xml
  src/main/java/com/stemcraft/feature/SMGameModeInventories.java
Labels: bug, enhancement

#36 Hotfix/mc-depend-fix
  pom.xml
  src/main/resources/plugin.yml
Labels: priority: normal

#48 Adds chat features
  README.md
  src/main/java/com/stemcraft/feature/SMChat.java
  src/main/resources/messages_en.yml
Labels: type: feature, priority: normal

#49 Add configuration sync
  README.md
  src/main/java/com/stemcraft/core/SMLocale.java
  src/main/java/com/stemcraft/core/config/SMConfigFile.java
Labels: type: feature, priority: low
